#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

sbt_build() {
    check_dependency_java

    cd $APP_HOME
    header "Running tests..."
    ./sbt test
}

build_in_sandbox() {
    cd $APP_HOME
    ./scripts/build-in-sandbox
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    build_in_sandbox
else
    sbt_build
fi

set +e
