#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Note: Windows Bash doesn't support shebang extra params
set -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/pcs-config-java"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    echo "Starting Config web service ..."
    docker run -it -p 9005:9005 \
        -e PCS_STORAGEADAPTER_WEBSERVICE_URL \
        -e PCS_DEVICESIMULATION_WEBSERVICE_URL \
        -e PCS_TELEMETRY_WEBSERVICE_URL \
        -e PCS_AZUREMAPS_KEY \
        -e PCS_AUTH_WEBSERVICE_URL \
        -e PCS_OFFICE365_CONNECTION_URL \
        -e PCS_SOLUTION_NAME \
        -e PCS_SUBSCRIPTION_ID \
        -e PCS_ARM_ENDPOINT_URL \
        "$DOCKER_IMAGE:testing"
}

run_container

set +e
