#!/usr/bin/env bash
# Copyright (c) Microsoft. All rights reserved.
# Note: Windows Bash doesn't support shebang extra params
set -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/pcs-config-java"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    echo "Starting Config web service ..."
    docker run -it -p 9005:9005 \
         -e PCS_KEYVAULT_NAME \
         -e PCS_AAD_APPID \
         -e PCS_AAD_APPSECRET \
        "$DOCKER_IMAGE:testing"
}

run_container

set +e
