#!/usr/bin/env bash

DOCKER_IMAGE="azureiotpcs/microservice-template-dotnet-ws:0.1-SNAPSHOT"

# quiet|minimal|normal|detailed|diagnostic
VERBOSITY=$1
# Debug|Release
CONFIGURATION=Release

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
cd $APP_HOME

if [[ -z "$VERBOSITY" ]]; then VERBOSITY="normal"; fi

cd WebService
dotnet restore
dotnet publish --output bin/docker --configuration $CONFIGURATION --verbosity $VERBOSITY

cd bin/docker
docker build --tag "$DOCKER_IMAGE" --squash --compress --label "Tags=azure,iot,pcs,.NET" .
