#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

sbt_compile() {
    check_dependency_java

    cd $APP_HOME
    ./sbt compile
}

compile_in_sandbox() {
    cd $APP_HOME
    ./scripts/compile-in-sandbox
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    compile_in_sandbox
else
    sbt_compile
fi

set +e
