#!/usr/bin/env bash -e

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

if [[ ${#APP_HOME} -lt 20 ]]; then
    error "Unable to detect current folder. Aborting."
    exit -1
fi

cd $APP_HOME

header "Removing temporary folders and files..."

rm -fR ./target/
rm -fR ./logs/
rm -fR ./project/target/
rm -fR ./project/project/

echo -e "\nDone"

set +e
