#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

if [[ ${#APP_HOME} -lt 20 ]]; then
    error "Unable to detect current folder. Aborting."
    exit 1
fi

cleanup_dotnetcore() {
    cd $APP_HOME/dotnet
    PROJECTS=$(dotnet sln list | grep 'csproj$')

    for PROJ in $PROJECTS; do
        PROJ=$(dirname "$PROJ")
        cd $PROJ
        rm -fR bin/
        rm -fR obj/
        cd $APP_HOME/dotnet
    done
}

cleanup_dotnetfwk() {
    cd $APP_HOME/dotnet4x

    rm -fR packages

    PROJECTS=$(dotnet sln list | grep 'csproj$')

    for PROJ in $PROJECTS; do
        PROJ=$(dirname "$PROJ")
        cd $PROJ
        rm -fR bin/
        rm -fR obj/
        cd $APP_HOME/dotnet4x
    done
}

cleanup_java() {
    cd $APP_HOME/java
    ./gradlew -q clean
    rm -fR ./build/
    rm -fR ./out/
}

header "Removing temporary folders and files..."
cleanup_dotnetcore
cleanup_dotnetfwk
cleanup_java
print "\nDone"
