#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

sbt_package() {
    check_dependency_java

    cd $APP_HOME
    chmod +x sbt
    ./sbt assembly && echo -n "Package available at: " && echo $(find target/scala-2.12 -name *.jar |grep assembly)
}

sbt_package

set +e
