#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/telemetry-java"

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    # Some settings are used to connect to an external dependency, e.g. Azure IoT Hub and IoT Hub Manager API
    # Depending on which settings and which dependencies are needed, edit the list of variables
    echo "Starting telemetry service..."
    docker run -it -p 9004:9004 \
        -e PCS_TELEMETRY_DOCUMENTDB_CONNSTRING \
        -e PCS_STORAGEADAPTER_WEBSERVICE_URL \
        "$DOCKER_IMAGE:testing"
}

run_container

set +e
