#!/usr/bin/env bash

set -e
APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

setup_cache() {
    cd $APP_HOME
    mkdir -p .cache/sandbox/.ivy2
    mkdir -p .cache/sandbox/.sbt
}

build_in_sandbox() {
    cd $APP_HOME

    # On Windows this script should use docker.exe, in which case
    # the parameters syntax is different, e.g. volumes path
    # (i.e. C:\path\path\... vs /c/path/path/...). Note that this
    # script is also used for the git precommit hook.
    set +e
    IS_WINDOWS=$(which cmd.exe)
    set -e
    if [[ -z "$IS_WINDOWS" ]]; then
        check_dependency_docker
        docker run \
            -v "$APP_HOME/.cache/sandbox/.ivy2:/root/.ivy2" \
            -v "$APP_HOME/.cache/sandbox/.sbt:/root/.sbt" \
            -v "$APP_HOME:/opt/code" \
            azureiotpcs/code-builder-java:1.0 /opt/scripts/build
    else
        cmd.exe /c ".\scripts\build-in-sandbox.cmd"
    fi
}

setup_cache
build_in_sandbox

set +e
