#!/usr/bin/env bash -e

# Usage:
# Run the service in the local environment:  ./scripts/run
# Run the service inside a Docker container: ./scripts/run -s
# Run the service inside a Docker container: ./scripts/run --in-sandbox

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

# Folder where PCS sandboxes cache data. Reuse the same folder to speed up the
# sandbox and to save disk space.
# Use PCS_CACHE="$APP_HOME/.cache" to cache inside the project folder
PCS_CACHE="/tmp/azure/iotpcs/.cache"

run() {
    cd $APP_HOME

    check_dependency_java
    ./scripts/env-vars-check

    echo "Starting Config service..."
    chmod +x sbt
    ./sbt "run 9005"
}

setup_sandbox_cache() {
    mkdir -p $PCS_CACHE/sandbox/.ivy2
    mkdir -p $PCS_CACHE/sandbox/.sbt
    echo "Note: caching build files in $PCS_CACHE"
}

run_in_sandbox() {

    setup_sandbox_cache

    cd $APP_HOME

    # In Windows this script should use docker.exe, in which case
    # the parameters syntax is different, e.g. volumes path
    # (i.e. C:\path\path\... vs /c/path/path/...).
    set +e
    IS_WINDOWS=$(which cmd.exe)
    set -e
    if [[ -z "$IS_WINDOWS" ]]; then
        check_dependency_docker

        ./scripts/env-vars-check

        # Note: the ports used must be exposed by `code-builder-java`
        #       see https://hub.docker.com/r/azureiotpcs/code-builder-java
        docker run -it \
            -p 9005:9005 \
            -e PCS_STORAGEADAPTER_WEBSERVICE_URL \
            -e PCS_DEVICESIMULATION_WEBSERVICE_URL \
            -e PCS_TELEMETRY_WEBSERVICE_URL \
            -e PCS_IOTHUBMANAGER_WEBSERVICE_URL \
            -e PCS_BINGMAP_KEY \
            -v "$PCS_CACHE/sandbox/.ivy2:/root/.ivy2" \
            -v "$PCS_CACHE/sandbox/.sbt:/root/.sbt" \
            -v "$APP_HOME:/opt/code" \
            azureiotpcs/code-builder-java:1.0 /opt/code/scripts/run
    else
        # Note 'winpty' is required to provide a TTY to Docker
        echo "Launching cmd.exe /c winpty ..."
        cmd.exe /c "winpty .\scripts\run.cmd --in-sandbox"
    fi
}

if [[ "$1" == "--in-sandbox" || "$1" == "-s" ]]; then
    run_in_sandbox
else
    run
fi

set +e
